"""user storage

Revision ID: 882c0f2409b0
Revises: aa413b6332c4
Create Date: 2025-02-18 02:09:25.469312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "882c0f2409b0"
down_revision: Union[str, None] = "aa413b6332c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    # ### end Alembic commands ###
